baseURL = 'https://drona-academy.netlify.app/'
languageCode = 'en-us'
title = 'Drona Academy'
theme = 'paige'
enablerobotstxt = true
titlecasestyle = "Go"

[params]
description = "Drona Academy - Empowering education and community through learning initiatives and charitable work"
author = "Drona Academy"
keywords = ["education", "learning", "charity", "community", "courses", "academy"]

[sitemap]
changefreq = "weekly"
priority = 0.5

[[module.imports]]


[languages.en]
weight = 10

[[languages.en.menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1

[[languages.en.menu.main]]
identifier = "charity"
name = "Karam Kodupom"
url = "/karam_kodupom"
weight = 2

[[languages.en.menu.main]]
identifier = "courses"
name = "Courses"
url = "/courses"
weight = 3

[[languages.en.menu.main]]
identifier = "competitions"
name = "Competitions"
url = "/competitions"
weight = 4

[[languages.en.menu.main]]
identifier = "alumni"
name = "Alumni"
url = "/success"
weight = 5

[[languages.en.menu.main]]
identifier = "about us"
name = "About Us"
url = "/about_us"
weight = 6

[[languages.en.menu.main]]
identifier = "contact us"
name = "Contact Us"
url = "/contact_us"
weight = 7

[[languages.en.menu.main]]
identifier = "eco friendly bags"
name = "Nandana Bags"
url = "/eco_friendly_bags"
weight = 8

[markup.goldmark.renderer]
unsafe = true

[taxonomies]
